name: Check links in markdown

on: push

jobs:
  test_links_in_readme:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: List files
        run: ls -la
      - uses: docker://pandoc/core:2.9
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --from markdown
            --output=mvr-spec.html
            mvr-spec.md
      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          path: mvr-spec.html
